[package]
name = "livebook-indicator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.15.5"
# gtk4 = "0.4.8"
libappindicator = "0.7.1"
